const data = [
    {
        key: 1,
        titleEN: "AR Experience",
        titleNL: "AR Ervaring",
        titleDE: "AR Erfahrung",
        photo: require('../../img/carousel/carousel1.png'),
        icon: require('../../img/carousel/cubeCarousel.png'),
        paginator: require('../../img/carousel/1.png'),
        contentEN: 'Aim your camera towards the floriade map and you will see a foot appear. This foot will show you how big of a piece of ground a person needs to live. Using the feet in the top-right corner you can switch between different sizes.',
        contentNL: 'Richt je camera op de kaart van Florida en je ziet een voet verschijnen. Deze voet laat zien hoe groot een stuk grond is dat iemand nodig heeft om te leven. Met de voetjes in de rechterbovenhoek kun je wisselen tussen verschillende maten.',
        contentDE: 'Richten Sie Ihre Kamera auf die Floriade-Karte und Sie werden einen Fuß sehen. Dieser Fuß zeigt Ihnen, wie viel Boden ein Mensch zum Leben braucht. Mit den Füßen in der oberen rechten Ecke können Sie zwischen verschiedenen Größen wechseln.'

    },
    {
        key: 2,
        titleEN: 'Map Experience',
        titleNL: 'Kaartervaring',
        titleDE: 'Kartenerfahrung',
        photo: require('../../img/carousel/carousel2.png'),
        icon: require('../../img/carousel/mapCarousel.png'),
        paginator: require('../../img/carousel/2.png'),
        contentEN: 'Two feet will be shown on the map in your screen. These foot will show the average dutch carbon footprint (in red) and the perfect one (in green). The blue point will be showing where you are located. While wandering about you will be able to see here if you are in one of the feet. This way you can get a feeling of the size of these feet and how much area you need.',
        contentNL: 'Twee voeten worden weergegeven op de kaart in uw scherm. Deze voet toont de gemiddelde Nederlandse CO2-voetafdruk (in rood) en de perfecte (in groen). Het blauwe punt geeft aan waar u zich bevindt. Terwijl je ronddwaalt, kun je hier zien of je in een van de voeten zit. Op deze manier kunt u een idee krijgen van de grootte van deze voeten en hoeveel ruimte u nodig heeft.',
        contentDE: 'Auf der Karte auf Ihrem Bildschirm werden zwei Fuß angezeigt. Diese Füße zeigen den durchschnittlichen niederländischen CO2-Fußabdruck (in Rot) und den perfekten (in Grün). Der blaue Punkt zeigt an, wo Sie sich befinden. Während Sie umherwandern, können Sie hier sehen, ob Sie sich in einem der Füße befinden. Auf diese Weise können Sie ein Gefühl dafür bekommen, wie groß diese Füße sind und wie viel Fläche Sie benötigen.'

    },
    {
        key: 3,
        title1EN: 'Carbon Footprint',
        title1NL: 'CO2-voetafdruk',
        title1DE: 'CO2-Fußabdruck',
        dutchFootContentEN: 'The Dutch carbon footprint',
        dutchFootContentNL: 'De Nederlandse CO2-voetafdruk',
        dutchFootContentDE: 'Der niederländische CO2-Fußabdruck',
        idealFootContentEN: 'The Ideal carbon footprint',
        idealFootContentNL: 'De ideale ecologische voetafdruk',
        idealFootContentDE: 'Der ideale CO2-Fußabdruck',
        personalFootContentEN: 'Your personal carbon footprint',
        personalFootContentNL: 'Uw persoonlijke ecologische voetafdruk',
        personalFootContentDE: 'Ihr persönlicher CO2-Fußabdruck',
        content1EN: 'You can switch between viewing the different footprints by selecting the feet show above.',
        content1NL: 'U kunt schakelen tussen het bekijken van de verschillende voetafdrukken door de hierboven getoonde voeten te selecteren.',
        content1DE: 'Sie können zwischen der Anzeige der verschiedenen Fußabdrücke wechseln, indem Sie die oben gezeigten Füße auswählen.',
        title2EN: 'Your personal carbon footprint',
        title2NL: 'Uw persoonlijke ecologische voetafdruk',
        title2DE: 'Ihr persönlicher CO2-Fußabdruck',
        content2EN: 'By selecting your personal carbon footprint you can calculate your own footprint. Answer the 12 questions by dragging the bar.',
        content2NL: 'Door uw persoonlijke ecologische voetafdruk te selecteren, kunt u uw eigen voetafdruk berekenen. Beantwoord de 12 vragen door de balk te verslepen.',
        content2DE: 'Durch die Auswahl Ihres persönlichen CO2-Fußabdrucks können Sie Ihren eigenen Fußabdruck berechnen. Beantworten Sie die 12 Fragen, indem Sie den Balken ziehen.',
        dataInfo1EN: 'Your data will not be saved',
        dataInfo1NL: 'Uw gegevens worden niet opgeslagen',
        dataInfo1DE: 'Ihre Daten werden nicht gespeichert',
        dataInfo2EN: 'Calculated carbon footprint is not fully accurate',
        dataInfo2NL: 'Berekende CO2-voetafdruk is niet volledig nauwkeurig',
        dataInfo2DE: 'Der berechnete CO2-Fußabdruck ist nicht ganz genau',
        photo: require('../../img/carousel/carousel3.png'),
        iconDutch: require('../../img/dutchFoot.png'),
        iconIdeal: require('../../img/idealFoot.png'),
        iconPersonal: require('../../img/personalFoot.png'),
        paginator: require('../../img/carousel/3.png'),
    }
];

export default data;